### PR TITLE
Added Player Icon (use Brawlify CDN)

### PR DESCRIPTION
**Pull request by Fastxyz**
- Add the Player **icon** property

e.g. using **discord.js**
```js
embed.setThumbnail(`https://cdn.brawlify.com/profile/${player.icon}.png`);
```

### CODE REVIEW

**Comment by Fastxyz** [comment]
@dannyhpy @wDiogolo

**Comment by dannyhpy** [comment]
I'm not sure if **Brawlify** would be okay if we scrap their API out of nowhere? :thinking:

**Comment by Fastxyz** [comment]
> I'm not sure if **Brawlify** would be okay if we scrap their API out of nowhere? 
> 
> **EDIT**: Nevermind, I thought you were using the CDN in the actual code which is not the case.

Will you add it?

**Comment by dannyhpy** [comment]
Added in https://github.com/dannyhpy/brawlstars-nodejs/commit/1c59d50c1e904b8301b40a449f0d05ca52d3bd45

**Pull request closed without merging**
